version: '3'
services:

# ==============   FastAPI Payment service.  ================
  payment:
    build: ./app_payment/app
    command: uvicorn --host 0.0.0.0 --port 5000 main:app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - marketplace

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - marketplace

# ===========================================================

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - marketplace

  megano:
    build: ./marketplace
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./marketplace:/app
    networks:
      - marketplace

  celery:
    build: ./marketplace
    command: celery -A marketplace worker -l info
    depends_on:
      - redis
    networks:
      - marketplace

networks:
  marketplace:
    driver: bridge