# Generated by Django 3.2.18 on 2023-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_to_cache",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Время кеширования"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
