# Generated by Django 3.2.18 on 2023-03-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="banners_cache_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Время кеширования баннеров"
            ),
        ),
    ]
