# Generated by Django 3.2.18 on 2023-03-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="static/assets/img/icons/", verbose_name="файл"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="наименование"),
                ),
            ],
            options={
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
            },
        ),
    ]
