# Generated by Django 3.2.18 on 2023-03-13 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_merch", "0002_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
    ]
