# Generated by Django 3.2.18 on 2023-03-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
        ("app_merch", "0005_banner_discount_offer_product_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="saller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offers",
                to="app_users.seller",
                verbose_name="продавец",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="offer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discounts",
                to="app_merch.offer",
                verbose_name="предложение",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_merch.image",
                verbose_name="медиа файл",
            ),
        ),
    ]
