# Generated by Django 3.2.18 on 2023-04-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_merch", "0011_offer_total_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="offer",
        ),
        migrations.AddField(
            model_name="discount",
            name="product",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discounts",
                to="app_merch.product",
                verbose_name="предложение",
            ),
        ),
        migrations.CreateModel(
            name="SetOfProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="set_of_products",
                        to="app_merch.Product",
                        verbose_name="продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор товаров",
                "verbose_name_plural": "Наборы товаров",
            },
        ),
        migrations.CreateModel(
            name="GroupDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_items",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="минимальное количество товаров в группе",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="group_discounts",
                        to="app_merch.Category",
                        verbose_name="категории",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_discounts",
                        to="app_merch.discount",
                        verbose_name="скидка",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="group_discounts",
                        to="app_merch.Product",
                        verbose_name="товары",
                    ),
                ),
            ],
            options={
                "verbose_name": "Групповая скидка",
                "verbose_name_plural": "Групповые скидки",
            },
        ),
    ]
