# Generated by Django 3.2.18 on 2023-04-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_merch", "0012_auto_20230427_0720"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="product_groups",
                        to="app_merch.Product",
                        verbose_name="продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа товаров",
                "verbose_name_plural": "Группы товаров",
            },
        ),
        migrations.CreateModel(
            name="SetDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка на набор",
                "verbose_name_plural": "Скидки на наборы",
            },
        ),
        migrations.RemoveField(
            model_name="setofproducts",
            name="products",
        ),
        migrations.AddField(
            model_name="discount",
            name="set_of_products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discounts",
                to="app_merch.setofproducts",
                verbose_name="набор товаров",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="product",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discounts",
                to="app_merch.product",
                verbose_name="продукт",
            ),
        ),
        migrations.DeleteModel(
            name="GroupDiscount",
        ),
        migrations.AddField(
            model_name="setdiscount",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="set_discounts",
                to="app_merch.discount",
                verbose_name="скидка",
            ),
        ),
        migrations.AddField(
            model_name="setdiscount",
            name="product_groups",
            field=models.ManyToManyField(
                db_index=True,
                related_name="set_discounts",
                to="app_merch.ProductGroup",
                verbose_name="группы товаров",
            ),
        ),
        migrations.AddField(
            model_name="setofproducts",
            name="product_groups",
            field=models.ManyToManyField(
                related_name="set_of_products",
                to="app_merch.ProductGroup",
                verbose_name="группы товаров",
            ),
        ),
    ]
