# Generated by Django 3.2.18 on 2023-05-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_merch', '0012_watchedproduct'),
        ('app_merch', '0014_cartdiscount'),
    ]

    operations = [
    ]
