# Generated by Django 3.2.18 on 2023-06-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_merch', '0017_auto_20230602_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='set_of_products',
        ),
        migrations.RemoveField(
            model_name='setdiscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='setdiscount',
            name='product_groups',
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='актуальность'),
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='is_percent',
            field=models.BooleanField(default=False, verbose_name='в процентах'),
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='приоритет'),
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='set_of_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='set_discounts', to='app_merch.setofproducts', verbose_name='Наборы товаров'),
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='size',
            field=models.PositiveIntegerField(null=True, verbose_name='размер'),
        ),
        migrations.AddField(
            model_name='setdiscount',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата начала'),
        ),
    ]
