# Generated by Django 3.2.18 on 2023-06-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_merch', '0018_auto_20230604_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='set_of_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='app_merch.setofproducts', verbose_name='набор товаров'),
        ),
    ]
