# Generated by Django 3.2.18 on 2023-06-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0001_initial'),
        ('app_merch', '0019_discount_set_of_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='set_of_products',
        ),
        migrations.AlterField(
            model_name='cartdiscount',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='app_basket.cart', unique=True, verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(help_text='Введите рейтинг от 1 до 5', verbose_name='Рейтинг'),
        ),
    ]
