# Generated by Django 3.2.18 on 2023-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_merch', '0020_auto_20230612_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='images', verbose_name='файл'),
        ),
    ]
