# Generated by Django 3.2.18 on 2023-04-07 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_merch", "0011_offer_total_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_users", "0003_buyer_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="тип")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="цена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип доставки",
                "verbose_name_plural": "Типы доставок",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("not_paid", "Не оплачен"), ("paid", "Оплачен")],
                        max_length=20,
                        verbose_name="статус оплаты",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="адрес")),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата заказа"),
                ),
                (
                    "departure_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата отправки"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата доставки"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("is_delivering", "Доставляется"),
                            ("delivered", "Доставлен"),
                        ],
                        max_length=20,
                        verbose_name="статус доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterField(
            model_name="buyer",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buyer",
                to="app_users.profile",
                verbose_name="покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="тип")),
                (
                    "credit_card",
                    models.CharField(max_length=8, verbose_name="номер счета"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="app_users.buyer",
                        verbose_name="покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип оплаты",
                "verbose_name_plural": "Типы оплаты",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="количество")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="app_merch.offer",
                        verbose_name="предложение",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="app_users.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказе",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="app_users.buyer",
                verbose_name="покупатель",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="app_users.deliverytype",
                verbose_name="тип доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="app_users.payment",
                verbose_name="тип оплаты",
            ),
        ),
    ]
