# Generated by Django 3.2.18 on 2023-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0004_auto_20230407_1806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="номер телефона"
            ),
        ),
    ]
