# Generated by Django 3.2.18 on 2023-04-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0005_alter_profile_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="тип оплаты")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
            ],
            options={
                "verbose_name": "тип оплаты",
                "verbose_name_plural": "типы оплаты",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="type",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Оплачен"), ("not_paid", "Не оплачен")],
                max_length=20,
                verbose_name="статус оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="app_users.paymenttype",
                verbose_name="тип оплаты",
            ),
            preserve_default=False,
        ),
    ]
