# Generated by Django 3.2.18 on 2023-05-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_merch", "0011_offer_total_views"),
        ("app_users", "0006_auto_20230423_0757"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttype",
            options={
                "verbose_name": "вид оплаты",
                "verbose_name_plural": "виды оплаты",
            },
        ),
        migrations.AlterField(
            model_name="buyer",
            name="views",
            field=models.ManyToManyField(
                null=True, to="app_merch.Product", verbose_name="история просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255, null=True, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="app_users.deliverytype",
                verbose_name="тип доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[("delivered", "Доставлен"), ("is_delivering", "Доставляется")],
                max_length=20,
                null=True,
                verbose_name="статус доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("not_paid", "Не оплачен"), ("paid", "Оплачен")],
                max_length=20,
                verbose_name="статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="title",
            field=models.CharField(max_length=100, verbose_name="вид оплаты"),
        ),
    ]
