# Generated by Django 3.2.18 on 2023-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0007_auto_20230507_0852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("not_paid", "Не оплачен"), ("paid", "Оплачен")],
                max_length=20,
                verbose_name="статус оплаты",
            ),
        ),
    ]
