# Generated by Django 3.2.18 on 2023-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_merch", "0011_offer_total_views"),
        ("app_users", "0007_auto_20230504_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="views",
            field=models.ManyToManyField(
                to="app_merch.Product", verbose_name="история просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[("is_delivering", "Доставляется"), ("delivered", "Доставлен")],
                max_length=20,
                null=True,
                verbose_name="статус доставки",
            ),
        ),
    ]
