# Generated by Django 3.2.18 on 2023-05-10 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0008_alter_order_payment_status"),
        ("app_users", "0010_auto_20230506_1004"),
    ]

    operations = []
