# Generated by Django 3.2.18 on 2023-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_auto_20230513_1029'),
        ('app_users', '0011_merge_20230510_0905'),
    ]

    operations = [
    ]
