# Generated by Django 3.2.18 on 2023-05-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_merge_20230513_1144'),
        ('app_users', '0012_merge_20230513_1342'),
    ]

    operations = [
    ]
