# Generated by Django 3.2.18 on 2023-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_auto_20230527_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'Доставлен'), ('is_delivering', 'Доставляется'), ('awaiting_payment', 'Ожидает оплаты')], max_length=20, null=True, verbose_name='статус доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Не оплачен'), ('paid', 'Оплачен')], max_length=20, verbose_name='статус оплаты'),
        ),
    ]
