# Generated by Django 3.2.18 on 2023-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_auto_20230601_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('is_delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('awaiting_payment', 'Ожидает оплаты')], max_length=20, null=True, verbose_name='статус доставки'),
        ),
    ]
