# Generated by Django 3.2.18 on 2023-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_auto_20230601_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('is_delivering', 'Доставляется'), ('awaiting_payment', 'Ожидает оплаты'), ('delivered', 'Доставлен')], max_length=20, null=True, verbose_name='статус доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Не оплачен'), ('paid', 'Оплачен')], max_length=20, verbose_name='статус оплаты'),
        ),
    ]
