# Generated by Django 3.2.18 on 2023-06-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0021_auto_20230602_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('is_delivering', 'Доставляется'), ('delivered', 'Доставлен')], max_length=20, null=True, verbose_name='статус доставки'),
        ),
    ]
