# Generated by Django 3.2.18 on 2023-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0024_auto_20230602_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('is_delivering', 'Доставляется'), ('awaiting_payment', 'Ожидает оплаты'), ('delivered', 'Доставлен')], max_length=20, null=True, verbose_name='статус доставки'),
        ),
    ]
