# Generated by Django 3.2.18 on 2023-06-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_auto_20230602_1952'),
        ('app_users', '0027_auto_20230602_1136'),
    ]

    operations = [
    ]
